WebApplicationForMilitaria/Controllers/FirstProviderFileTwoController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplicationForMilitaria.Application.ApplicationUser;
using WebApplicationForMilitaria.Application.FirstProviderFileTwo.Commands.CreateFirstProviderTwoFile;
using WebApplicationForMilitaria.Application.FirstProviderFileTwo.Commands.DeleteFirstProviderTwoFile;
using WebApplicationForMilitaria.Application.FirstProviderFileTwo.Commands.SaveNewRecordsFirstProviderTwoFile;
using WebApplicationForMilitaria.Application.FirstProviderFileTwo.Queries.GetAllRecordsFirstProviderTwoFile;
using WebApplicationForMilitaria.Application.FirstProviderFileTwo.Queries.GetRecordByIdFirstProviderTwoFile;
using WebApplicationForMilitaria.Application.SecondProviderFileTwo.Commands.CreateSecondProviderTwoFile;
using WebApplicationForMilitaria.Application.SecondProviderFileTwo.Commands.DeleteSecondProviderTwoFile;
using WebApplicationForMilitaria.Application.SecondProviderFileTwo.Queries.GetRecordByIdSecondProviderTwoFile;

namespace WebApplicationForMilitaria.MVC.Controllers
{
    public class FirstProviderFileTwoController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;
        private readonly INotyfService _toastService;
        private static bool isUse {  get; set; } = true;

        public FirstProviderFileTwoController(IMediator mediator, IMapper mapper, INotyfService toastService)
        {
            _mediator = mediator;
            _mapper = mapper;
            _toastService = toastService;
        }

        public async Task<IActionResult> Index()
        {
            var records = await _mediator.Send(new GetAllRecordsFirstProviderTwoFileQuery());

            if (records == null || (records.Count() == 0 && isUse == true))
            {
                await _mediator.Send(new SaveNewRecordsFirstProviderTwoFileCommand());
                records = await _mediator.Send(new GetAllRecordsFirstProviderTwoFileQuery());
                isUse = false;
            }
            return View(records);
        }

        [Authorize]
        public IActionResult Create()
        {
            //if (User.Identity == null || !User.Identity.IsAuthenticated)
            //{
            //    return RedirectToPage("/Account/Login", new { area = "Identity" });
            //}

            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateFirstProviderTwoFileCommand product)
        {

            if (!ModelState.IsValid)
            {
                _toastService.Error("No Product Added");
                return View(product);
            }

            await _mediator.Send(product);
            _toastService.Success("Product Added");
            return RedirectToAction(nameof(Index));
        }

        [Route("FirstProviderFileTwo/{id}/Details")]
        public async Task<IActionResult> Details(int id)
        {
            CurrentUser.IdRecord = id;
            var productDto = await _mediator.Send(new GetRecordByIdFirstProviderTwoFileQuery(id));
            return View(productDto);
        }

        [Route("FirstProviderFileTwo/{id}/Delete")]
        public async Task<IActionResult> Delete(int id)
        {
            var productDto = await _mediator.Send(new GetRecordByIdFirstProviderTwoFileQuery(id));

            await _mediator.Send(new DeleteFirstProviderTwoFileCommand(id));
            _toastService.Success("Deleted given Project");
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApplicationForMilitaria/Views/FirstProviderFileTwo/Create.cshtml
@model WebApplicationForMilitaria.Application.FirstProviderFileTwo.Commands.CreateFirstProviderTwoFile.CreateFirstProviderTwoFileCommand

<h4>CreateFirstProviderTwoFileCommand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="ProductIdXML" class="control-label"></label>
                <input asp-for="ProductIdXML" class="form-control" />
                <span asp-validation-for="ProductIdXML" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProducerId" class="control-label"></label>
                <input asp-for="ProducerId" class="form-control" />
                <span asp-validation-for="ProducerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <input asp-for="CategoryId" class="form-control" />
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitId" class="control-label"></label>
                <input asp-for="UnitId" class="form-control" />
                <span asp-validation-for="UnitId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WarrantyId" class="control-label"></label>
                <input asp-for="WarrantyId" class="form-control" />
                <span asp-validation-for="WarrantyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CardUrl" class="control-label"></label>
                <input asp-for="CardUrl" class="form-control" />
                <span asp-validation-for="CardUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceNet" class="control-label"></label>
                <input asp-for="PriceNet" class="form-control" />
                <span asp-validation-for="PriceNet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceGross" class="control-label"></label>
                <input asp-for="PriceGross" class="form-control" />
                <span asp-validation-for="PriceGross" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SrvNet" class="control-label"></label>
                <input asp-for="SrvNet" class="form-control" />
                <span asp-validation-for="SrvNet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SrvGross" class="control-label"></label>
                <input asp-for="SrvGross" class="form-control" />
                <span asp-validation-for="SrvGross" class="text-danger"></span>
            </div>
            
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsEditable" /> @Html.DisplayNameFor(model => model.IsEditable)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationForMilitaria/Views/FirstProviderFileTwo/Details.cshtml
@model WebApplicationForMilitaria.Application.FirstProviderFileTwo.ProductTwoDto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductIdXML)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductIdXML)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProducerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProducerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WarrantyId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WarrantyId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CardUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CardUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PriceNet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PriceNet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PriceGross)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PriceGross)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SrvNet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SrvNet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SrvGross)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SrvGross)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedById)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedById)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsEditable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsEditable)
        </dd>
    </dl>
</div>
<div>
    
    <a class="btn btn-outline-secondary" asp-action="Index">Back to List</a>
</div>

WebApplicationForMilitaria/Views/FirstProviderFileTwo/Index.cshtml
@model IEnumerable<WebApplicationForMilitaria.Application.FirstProviderFileTwo.ProductTwoDto>


<h1>List Of FirstProviderFileTwo</h1>

<p>
    <a asp-action="Create" class="btn btn-secondary">Create</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductIdXML)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProducerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UnitId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WarrantyId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CardUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceNet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceGross)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SrvNet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SrvGross)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedById)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsEditable)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductIdXML)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProducerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WarrantyId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CardUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceNet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceGross)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SrvNet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SrvGross)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedById)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsEditable)
            </td>
            <td>
                    <a class="btn btn-outline-secondary" asp-controller="FirstProviderFileTwo" asp-action="Details" asp-route-id="@item.Id">Details</a>


                    @if (item.IsEditable)
                    {
                        <a class="btn btn-outline-secondary" asp-controller="FirstProviderFileTwo" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>