WebApplicationForMilitaria/Controllers/SecondProviderFileOneController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplicationForMilitaria.Application.SecondProviderFileOne.Commands.CreateSecondProviderOneFile;
using WebApplicationForMilitaria.Application.SecondProviderFileOne.Commands.DeleteSecondProviderOneFile;
using WebApplicationForMilitaria.Application.SecondProviderFileOne.Commands.EditSecondProviderOneFile;
using WebApplicationForMilitaria.Application.SecondProviderFileOne.Queries.GetAllRecordsSecondProviderOneFile;
using WebApplicationForMilitaria.Application.SecondProviderFileOne.Queries.GetRecordByIdSecondProviderOneFile;

namespace WebApplicationForMilitaria.MVC.Controllers
{
    public class SecondProviderFileOneController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;
        private readonly INotyfService _toastService;

        public SecondProviderFileOneController(IMediator mediator, IMapper mapper, INotyfService notyfService)
        { 
            _mediator = mediator;
            _mapper = mapper;
            _toastService = notyfService;
        }

        public async Task<IActionResult> Index()
        {
            var records = await _mediator.Send(new GetAllRecordsSecondProviderOneFileQuery());
            
            return View(records);
        }


        [Authorize]
        public IActionResult Create()
        {
            return View();
        }


        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateSecondProviderOneFileCommand product)
        {
            if (!ModelState.IsValid)
            {
                _toastService.Error("No Product Added");
                return View(product);
            }


            await _mediator.Send(product);
            _toastService.Success("Added new Product");
            return RedirectToAction(nameof(Index));
        }

        [Route("SecondProviderFileOne/{id}/Edit")]
        public async Task<IActionResult> Edit(int id)
        {
            var productDto = await _mediator.Send(new GetRecordByIdSecondProviderOneFileQuery(id));


            // _toastService.Error("no product updated");

            var model = _mapper.Map<EditSecondProviderOneFileCommand>(productDto);

            return View(model);
        }

        [HttpPost]
        [Route("SecondProviderFileOne/{id}/Edit")]
        public async Task<IActionResult> Edit(int id, EditSecondProviderOneFileCommand product)
        {
            
            

            await _mediator.Send(product);
            _toastService.Success("Updated given Product");
            return RedirectToAction(nameof(Index));
        }

        [Route("SecondProviderFileOne/{id}/Details")]
        public async Task<IActionResult> Details(int id)
        {
            var productDto = await _mediator.Send(new GetRecordByIdSecondProviderOneFileQuery(id));
            return View(productDto);
        }

        [Route("SecondProviderFileOne/{id}/Delete")]
        public async Task<IActionResult> Delete(int id)
        {
            await _mediator.Send(new DeleteSecondProviderOneFileCommand(id));
            _toastService.Success("Deleted given Product");
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApplicationForMilitaria/Views/SecondProviderFileOne/Create.cshtml
@model WebApplicationForMilitaria.Application.SecondProviderFileOne.Commands.CreateSecondProviderOneFile.CreateSecondProviderOneFileCommand

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CreateSecondProviderOneFileCommand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group mb-3">
                <label asp-for="Ean" class="control-label"></label>
                <input asp-for="Ean" class="form-control" />
                <span asp-validation-for="Ean" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Sku" class="control-label"></label>
                <input asp-for="Sku" class="form-control" />
                <span asp-validation-for="Sku" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="InStock" class="control-label"></label>
                <input asp-for="InStock" class="form-control" />
                <span asp-validation-for="InStock" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Qty" class="control-label"></label>
                <input asp-for="Qty" class="form-control" />
                <span asp-validation-for="Qty" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Availability" class="control-label"></label>
                <input asp-for="Availability" class="form-control" />
                <span asp-validation-for="Availability" class="text-danger"></span>
            </div>
            
            <div class="form-group mb-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationForMilitaria/Views/SecondProviderFileOne/Details.cshtml
@model WebApplicationForMilitaria.Application.SecondProviderFileOne.ProductThreeDto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ean)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ean)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sku)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sku)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InStock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InStock)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Qty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Qty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Availability)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Availability)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductIdFromXML)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductIdFromXML)
        </dd>
    </dl>
</div>
<div>
    @if (Model.IsEditable)
    {
        <a class="btn btn-outline-secondary" asp-controller="SecondProviderFileOne" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    }

    <a class="btn btn-outline-secondary" asp-action="Index">Back to List</a>
</div>

WebApplicationForMilitaria/Views/SecondProviderFileOne/Edit.cshtml
@model WebApplicationForMilitaria.Application.SecondProviderFileOne.Commands.EditSecondProviderOneFile.EditSecondProviderOneFileCommand

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Ean" class="control-label"></label>
                <input asp-for="Ean" class="form-control" />
                <span asp-validation-for="Ean" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Sku" class="control-label"></label>
                <input asp-for="Sku" class="form-control" />
                <span asp-validation-for="Sku" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="InStock" class="control-label"></label>
                <input asp-for="InStock" class="form-control" />
                <span asp-validation-for="InStock" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Qty" class="control-label"></label>
                <input asp-for="Qty" class="form-control" />
                <span asp-validation-for="Qty" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Availability" class="control-label"></label>
                <input asp-for="Availability" class="form-control" />
                <span asp-validation-for="Availability" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="ProductIdFromXML" class="control-label"></label>
                <input asp-for="ProductIdFromXML" class="form-control" readonly />
                <span asp-validation-for="ProductIdFromXML" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationForMilitaria/Views/SecondProviderFileOne/Index.cshtml
@model IEnumerable<WebApplicationForMilitaria.Application.SecondProviderFileOne.ProductThreeDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Lists Of SecondProviderOneFile</h1>

<p>
    <a asp-action="Create" class="btn btn-secondary">Create </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ean)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sku)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InStock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Qty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Availability)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductIdFromXML)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ean)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sku)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InStock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Availability)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductIdFromXML)
            </td>
            <td>
                    <a class="btn btn-outline-secondary" asp-controller="SecondProviderFileOne" asp-action="Details" asp-route-id="@item.Id">Details</a>


                    @if (item.IsEditable)
                    {
                        <a class="btn btn-outline-secondary" asp-controller="SecondProviderFileOne" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        <a class="btn btn-outline-secondary" asp-controller="SecondProviderFileOne" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>