WebApplicationForMilitaria/Controllers/ThirdProviderFileOneController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplicationForMilitaria.Application.ApplicationUser;
using WebApplicationForMilitaria.Application.SecondProviderFileTwo.Commands.EditSecondProviderTwoFile;
using WebApplicationForMilitaria.Application.SecondProviderFileTwo.Queries.GetRecordByIdSecondProviderTwoFile;
using WebApplicationForMilitaria.Application.ThirdProviderFileOne.Commands.CreateThirdProviderOneFile;
using WebApplicationForMilitaria.Application.ThirdProviderFileOne.Commands.DeleteThirdProviderOneFile;
using WebApplicationForMilitaria.Application.ThirdProviderFileOne.Commands.EditThirdProviderOneFile;
using WebApplicationForMilitaria.Application.ThirdProviderFileOne.Queries.GetAllRecords;
using WebApplicationForMilitaria.Application.ThirdProviderFileOne.Queries.GetRecordByIdThirdProviderOneFile;

namespace WebApplicationForMilitaria.MVC.Controllers
{
    public class ThirdProviderFileOneController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;
        private readonly INotyfService _toastService;
        public ThirdProviderFileOneController(IMediator mediator, IMapper mapper, INotyfService toastService)
        {
            _mediator = mediator;
            _mapper = mapper;
            _toastService = toastService;
        }

        public async Task<IActionResult> Index()
        {
            var records = await _mediator.Send(new GetAllRecordsThirdProviderOneFileQuery());

            return View(records);
        }

        [Authorize]
        public IActionResult Create()
        {
            //if (User.Identity == null || !User.Identity.IsAuthenticated)
            //{
            //    return RedirectToPage("/Account/Login", new { area = "Identity" });
            //}

            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateThirdProviderOneFileCommand product)
        {

            if (!ModelState.IsValid)
            {
                _toastService.Error("No Product Added");
                return View(product);
            }

            await _mediator.Send(product);
            _toastService.Success("Product Added");
            return RedirectToAction(nameof(Index));
        }

        [Route("ThirdProviderFileOne/{id}/Details")]
        public async Task<IActionResult> Details(int id)
        {
            CurrentUser.IdRecord = id;
            var productDto = await _mediator.Send(new GetRecordByIdThirdProviderOneFileQuery(id));
            return View(productDto);
        }

        [Route("ThirdProviderFileOne/{id}/Delete")]
        public async Task<IActionResult> Delete(int id)
        {
            var productDto = await _mediator.Send(new GetRecordByIdThirdProviderOneFileQuery(id));

            await _mediator.Send(new DeleteThirdProviderOneFileCommand(id));
            _toastService.Success("Deleted given Project");
            return RedirectToAction(nameof(Index));
        }

        [Route("ThirdProviderFileOne/{id}/Edit")]
        public async Task<IActionResult> Edit(int id)
        {
            var productDto = await _mediator.Send(new GetRecordByIdThirdProviderOneFileQuery(id));

            if (!productDto.IsEditable)
            {
                _toastService.Error("no product updated -> you don't have access, only his creator");
                return RedirectToAction(nameof(Index));
            }

            var model = _mapper.Map<EditThirdProviderOneFileCommand>(productDto);

            return View(model);
        }

        [HttpPost]
        [Route("ThirdProviderFileOne/{id}/Edit")]
        public async Task<IActionResult> Edit(int id, EditThirdProviderOneFileCommand product)
        {
            await _mediator.Send(product);
            _toastService.Success("Updated given product");
            return RedirectToAction(nameof(Index));
        }

    }
}

WebApplicationForMilitaria/Views/ThirdProviderFileOne/Create.cshtml
@model WebApplicationForMilitaria.Application.ThirdProviderFileOne.Commands.CreateThirdProviderOneFile.CreateThirdProviderOneFileCommand

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamePl" class="control-label"></label>
                <input asp-for="NamePl" class="form-control" />
                <span asp-validation-for="NamePl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NameEn" class="control-label"></label>
                <input asp-for="NameEn" class="form-control" />
                <span asp-validation-for="NameEn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionPl" class="control-label"></label>
                <input asp-for="DescriptionPl" class="form-control" />
                <span asp-validation-for="DescriptionPl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionEn" class="control-label"></label>
                <input asp-for="DescriptionEn" class="form-control" />
                <span asp-validation-for="DescriptionEn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ean" class="control-label"></label>
                <input asp-for="Ean" class="form-control" />
                <span asp-validation-for="Ean" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WholesalePrice" class="control-label"></label>
                <input asp-for="WholesalePrice" class="form-control" />
                <span asp-validation-for="WholesalePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SuggestedPrice" class="control-label"></label>
                <input asp-for="SuggestedPrice" class="form-control" />
                <span asp-validation-for="SuggestedPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierCode" class="control-label"></label>
                <input asp-for="SupplierCode" class="form-control" />
                <span asp-validation-for="SupplierCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vat" class="control-label"></label>
                <input asp-for="Vat" class="form-control" />
                <span asp-validation-for="Vat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Size" class="control-label"></label>
                <input asp-for="Size" class="form-control" />
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryPl" class="control-label"></label>
                <input asp-for="CategoryPl" class="form-control" />
                <span asp-validation-for="CategoryPl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryEn" class="control-label"></label>
                <input asp-for="CategoryEn" class="form-control" />
                <span asp-validation-for="CategoryEn" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationForMilitaria/Views/ThirdProviderFileOne/Details.cshtml
@model WebApplicationForMilitaria.Application.ThirdProviderFileOne.ProductFiveDto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>


<div>
    
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NamePl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NamePl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameEn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameEn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescriptionPl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescriptionPl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescriptionEn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescriptionEn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ean)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ean)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WholesalePrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WholesalePrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SuggestedPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SuggestedPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SupplierCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SupplierCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Size)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryPl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryPl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryEn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryEn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsEditable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsEditable)
        </dd>
    </dl>
</div>
<div>
    @if (Model.IsEditable)
    {
        <a class="btn btn-outline-secondary" asp-controller="ThirdProviderFileOne" asp-action="Edit" asp-route-id="@Model.ProductId">Edit</a>
    }

    <a class="btn btn-outline-secondary" asp-action="Index">Back to List</a>
</div>

WebApplicationForMilitaria/Views/ThirdProviderFileOne/Edit.cshtml
@model WebApplicationForMilitaria.Application.ThirdProviderFileOne.Commands.EditThirdProviderOneFile.EditThirdProviderOneFileCommand


@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <input asp-for="ProductId" class="form-control" readonly />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamePl" class="control-label"></label>
                <input asp-for="NamePl" class="form-control" />
                <span asp-validation-for="NamePl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NameEn" class="control-label"></label>
                <input asp-for="NameEn" class="form-control" />
                <span asp-validation-for="NameEn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionPl" class="control-label"></label>
                <input asp-for="DescriptionPl" class="form-control" />
                <span asp-validation-for="DescriptionPl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionEn" class="control-label"></label>
                <input asp-for="DescriptionEn" class="form-control" />
                <span asp-validation-for="DescriptionEn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ean" class="control-label"></label>
                <input asp-for="Ean" class="form-control" />
                <span asp-validation-for="Ean" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WholesalePrice" class="control-label"></label>
                <input asp-for="WholesalePrice" class="form-control" />
                <span asp-validation-for="WholesalePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SuggestedPrice" class="control-label"></label>
                <input asp-for="SuggestedPrice" class="form-control" />
                <span asp-validation-for="SuggestedPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierCode" class="control-label"></label>
                <input asp-for="SupplierCode" class="form-control" />
                <span asp-validation-for="SupplierCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vat" class="control-label"></label>
                <input asp-for="Vat" class="form-control" />
                <span asp-validation-for="Vat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Size" class="control-label"></label>
                <input asp-for="Size" class="form-control" />
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryPl" class="control-label"></label>
                <input asp-for="CategoryPl" class="form-control" />
                <span asp-validation-for="CategoryPl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryEn" class="control-label"></label>
                <input asp-for="CategoryEn" class="form-control" />
                <span asp-validation-for="CategoryEn" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

div>
<a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationForMilitaria/Views/ThirdProviderFileOne/Index.cshtml
@model IEnumerable<WebApplicationForMilitaria.Application.ThirdProviderFileOne.ProductFiveDto>


@{
    ViewData["Title"] = "Index";
}

<h1>List Of ThirdProviderFileOne</h1>

<p>
    <a asp-action="Create" class="btn btn-secondary">Create </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NamePl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NameEn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescriptionPl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescriptionEn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ean)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WholesalePrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SuggestedPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SupplierCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryPl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryEn)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NamePl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NameEn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescriptionPl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescriptionEn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ean)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WholesalePrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SuggestedPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SupplierCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Size)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryPl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryEn)
            </td>
            <td>
                    <a class="btn btn-outline-secondary" asp-controller="ThirdProviderFileOne" asp-action="Details" asp-route-id="@item.ProductId">Details</a>


                    @if (item.IsEditable)
                    {
                        <a class="btn btn-outline-secondary" asp-controller="ThirdProviderFileOne" asp-action="Edit" asp-route-id="@item.ProductId">Edit</a>
                        <a class="btn btn-outline-secondary" asp-controller="ThirdProviderFileOne" asp-action="Delete" asp-route-id="@item.ProductId">Delete</a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>




@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    
}